# This script requires the following secrets to be set in the repository settings:
# - GITLAB_AUTH_HEADER_VALUE
# - PERSONAL_TOKEN
# - SELF_PASSWORD
#

name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ===== SETUPS ======

      - name: Setup codebase
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: "Setup Python3"
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2


      # ===== BUILD ======


      - name: Execute Gradle build
        run: gradle build


      # ===== EXTERNAL SCRIPTS =====


      - name: External scripts
        run: |
          wget -O tmp-environment_variables.sh https://raw.githubusercontent.com/L1ghtDream/report/cdn/environment_variables.sh
          chmod +x tmp-environment_variables.sh
          ./tmp-environment_variables.sh ${{ github.REPOSITORY }}
          
          mkdir -p tmp
          cd tmp
          wget https://raw.githubusercontent.com/L1ghtDream/report/cdn/README-template.md


      # ===== PUBLISH ======


      - name: Uploading artifacts
        run: |
          wget -O tmp-publish.sh https://raw.githubusercontent.com/L1ghtDream/report/cdn/publish.sh 
          chmod +x tmp-publish.sh 
          ./tmp-publish.sh ${{ secrets.GITLAB_AUTH_HEADER_VALUE }} ${{ github.REPOSITORY }} ${{ secrets.GITHUB_TOKEN }} ${{ secrets.SELF_PASSWORD }}

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.VERSION }}"
          prerelease: false
          title: "${{ env.VERSION }}"
          files: |
            build/libs/*.jar


      # ===== RENDERS ======


      - name: "README.md Render"
        uses: varunsridharan/action-dynamic-readme@main
        with:
          committer_name: "Radu Voinea"
          committer_email: "contact@voienaradu.com"
          commit_message: "Updated README.md versions"
          files: |
            tmp/README-template.md=README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
          ARTIFACT: ${{ env.ARTIFACT }}
          GROUP: ${{ env.GROUP }}
          GITHUB_USERNAME: ${{ github.REPOSITORY_OWNER }}
          REPOSITORY: ${{ github.REPOSITORY }}
          REPOSITORY_NAME: ${{ env.REPOSITORY_NAME }}

      - name: "Updating remote report"
        run: |
          wget -O tmp-update_report.sh https://raw.githubusercontent.com/L1ghtDream/report/cdn/update_report.sh
          chmod +x tmp-update_report.sh
          ./tmp-update_report.sh https://github.com/L1ghtDream/report ${{ env.ARTIFACT }} ${{ env.VERSION }} ${{ secrets.PERSONAL_TOKEN }}
